Update docker build system:
- move to Fedora as CentOS is deprecated and build fails:

RuntimeError: uvloop requires Python 3.7 or greater

- switch to dnf as yum is also deprecated

- clear all warnings that show up when doing `docker build ...'

- sort list of packages to install alphabetically

- use an explicit tag in FROM to be more future-proof

- simplify docker-run.sh